config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("", include("account.urls", namespace="account")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    # List
    path('', views.list_view, name="list_view"),
    # List Delete
    path('list/<slug:list_slug>/delete',
         views.list_delete_view, name="list_delete_view"),

    # TO-DO Filter
    path('list/<slug:list_slug>/todos/', views.todo_view, name="todo_view"),
    path('list/<slug:list_slug>/todos/completed/',
         views.todo_completed_view, name="todo_completed_view"),
    path('list/<slug:list_slug>/todos/uncompleted/',
         views.todo_uncompleted_view, name="todo_uncompleted_view"),
    path('list/<slug:list_slug>/todos/favorited/',
         views.todo_favorited_view, name="todo_favorited_view"),
    # TO-DO Toggle-Comleted
    path('toggle-completed/<slug:list_slug>/<slug:todo_slug>/',
         views.toggle_completed_view, name='toggle_completed_view'),
    # TO-DO Favorite
    path('list/<slug:list_slug>/todo/<slug:todo_slug>/add-favorite/',
         views.add_favorite_view, name="add_favorite_view"),
    path('list/<slug:list_slug>/todo/<slug:todo_slug>/remove-favorite/',
         views.remove_favorite_view, name="remove_favorite_view"),
    # TO-DO Update
    path('list/<slug:list_slug>/todo/<slug:todo_slug>/update/',
         views.todo_update_view, name="todo_update_view"),
    # TO-DO Delete
    path('list/<slug:list_slug>/todo/<slug:todo_slug>/delete/',
         views.todo_delete_view, name="todo_delete_view"),
    path('list/<slug:list_slug>/todos/delete-all',
         views.todo_delete_all_view, name="todo_delete_all_view"),
    # TO-DO Detail
    path('list/<slug:list_slug>/todo/<slug:todo_slug>/',
         views.todo_detail_view, name="todo_detail_view"),

    # Trash
    path('trash/', views.trash_view, name="trash_view"),
    path('trash/todo/<slug:todo_slug>/restore/',
         views.restore_todo_view, name="restore_todo_view"),
    path('trash/todo/<slug:todo_slug>/permanently-delete/',
         views.permanently_delete_todo_view, name="permanently_delete_todo_view"),
    path('empty-trash/', views.empty_trash_view, name="empty_trash_view"),
]

todo/models.py
from autoslug import AutoSlugField
from django.db import models
from django.contrib.auth.models import User


class List(models.Model):
    user = models.ForeignKey(User, verbose_name=(
        "İstifadəçi Adı"), on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(verbose_name="Başlıq", max_length=255)
    is_active = models.BooleanField(verbose_name="Aktiv", default=True)
    created_at = models.DateTimeField(
        verbose_name="Yaradılma Vaxtı", auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name="Yenilənmə Vaxtı", auto_now=True)
    slug = AutoSlugField(populate_from='title', unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = ("Siayhı")
        verbose_name_plural = ("Siyahılar")


class Todo(models.Model):
    list = models.ForeignKey(List, related_name='list_todos', verbose_name=(
        "Siyahı"), on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name=(
        "İstifadəçi Adı"), on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(verbose_name="Başlıq", max_length=255)
    description = models.TextField(
        verbose_name="Aşıqlama", null=True, blank=True)
    is_active = models.BooleanField(verbose_name="Aktiv", default=True)
    is_completed = models.BooleanField(
        verbose_name="Tamamlandı", default=False)
    created_at = models.DateTimeField(
        verbose_name="Yaradılma Vaxtı", auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name="Yenilənmə Vaxtı", auto_now=True)
    is_deleted = models.BooleanField(verbose_name="Silindi", default=False)
    slug = AutoSlugField(populate_from='title', unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = ("Todo")
        verbose_name_plural = ("Todolar")


class Favorite(models.Model):
    user = models.OneToOneField(
        User, related_name='favorited_by', on_delete=models.CASCADE, verbose_name=("İstifadəçi"))
    todos = models.ManyToManyField(
        'Todo', related_name='favorites', verbose_name=("Favorilər"))

    def __str__(self):
        return f"{self.user}"

    def add_todo_to_favorites(self, todo):
        self.todos.add(todo)

    def remove_todo_from_favorites(self, todo):
        self.todos.remove(todo)

    class Meta:
        verbose_name = ("Favori")
        verbose_name_plural = ("Favorilər")

todo/forms.py
from django import forms
from .models import List, Todo


class ListForm(forms.ModelForm):
    title = forms.CharField(
        max_length=80,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Yeni siyahı"}),
        required=True,
    )

    class Meta:
        model = List
        fields = ["title"]
        labels = {
            "title": "Siyahı Başlığı"
        }


class TodoForm(forms.ModelForm):
    title = forms.CharField(
        max_length=80,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Yeni tapşırıq"}),
        required=True,
    )

    class Meta:
        model = Todo
        fields = ["title"]
        labels = {
            "title": "Todo Başlığı"
        }


class TodoDetailForm(forms.ModelForm):
    title = forms.CharField(
        max_length=80,
        widget=forms.TextInput(
            attrs={"class": "form-control"}),
        required=True,
        label="Todo Başlığı"
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={"class": "form-control"}),
        required=False,
        label="Açıqlama"
    )

    class Meta:
        model = Todo
        fields = ["title", "description"]

todo/views.py
from django.http import HttpResponseForbidden, JsonResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import List, Todo, Favorite
from .forms import ListForm, TodoForm, TodoDetailForm


# ========== List ==========

@login_required(login_url="account:login_view")
def list_view(request):
    todo_lists = List.objects.filter(
        is_active=True, user=request.user).order_by("-updated_at")

    form = ListForm()

    if request.method == "POST":
        form = ListForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            todo_list = List.objects.create(title=title, user=request.user)
            return redirect("todo:list_view")

    for list_item in todo_lists:
        list_item.todos_count = list_item.list_todos.filter(
            is_active=True, is_deleted=False).count()

    context = {
        "todo_lists": todo_lists,
        "form": form,
    }
    return render(request, "todo/list.html", context)


@login_required(login_url="account:login_view")
def list_delete_view(request, list_slug):
    todo_list = get_object_or_404(List, slug=list_slug)

    if todo_list.user != request.user:
        return HttpResponseForbidden("Bu listə icazəniz yoxdur.")

    todo_list.delete()
    messages.success(request, f"Siyahı '{todo_list.title}' silindi!")
    return redirect(request.META.get('HTTP_REFERER', 'todo:list_view'))

# ========== END List ==========


# ========== Todo ==========

@login_required(login_url="account:login_view")
def todo_view(request, list_slug):
    todo_list = get_object_or_404(List, slug=list_slug)

    if todo_list.user != request.user:
        return HttpResponseForbidden("Bu listə icazəniz yoxdur.")

    todos = Todo.objects.filter(
        is_active=True, is_deleted=False, user=request.user, list=todo_list).order_by("-updated_at")
    favorites = todos.filter(favorites__user=request.user)
    form = TodoForm()

    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            todo = Todo.objects.create(
                title=title, user=request.user, list=todo_list)
            return redirect("todo:todo_view", list_slug=list_slug)

    context = {
        "todo_list": todo_list,
        "todos": todos,
        "favorites": favorites,
        "form": form,
    }
    return render(request, "todo/todo.html", context)


@login_required(login_url="account:login_view")
def toggle_completed_view(request, list_slug, todo_slug):
    todo = get_object_or_404(Todo, list__slug=list_slug, slug=todo_slug)

    if todo.is_deleted:
        raise Http404("Bu tapşırıq silinib.")

    if todo.user != request.user:
        return HttpResponseForbidden("Bu tapşırığa icazəniz yoxdur.")

    todo.is_completed = not todo.is_completed
    todo.save()
    return JsonResponse({'success': True})


@login_required(login_url="account:login_view")
def todo_completed_view(request, list_slug):
    todo_list = get_object_or_404(List, slug=list_slug)

    if todo_list.user != request.user:
        return HttpResponseForbidden("Bu listə icazəniz yoxdur.")

    todos = Todo.objects.filter(
        is_active=True, is_deleted=False, user=request.user, list__slug=list_slug, is_completed=True).order_by("-updated_at")
    favorites = todos.filter(favorites__user=request.user)
    form = TodoForm()

    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            todo = Todo.objects.create(
                title=title, user=request.user, list=todo_list)
            return redirect("todo:todo_view", list_slug=list_slug)

    context = {
        "todo_list": todo_list,
        "todos": todos,
        "favorites": favorites,
        "form": form,
    }
    return render(request, "todo/todo.html", context)


@login_required(login_url="account:login_view")
def todo_uncompleted_view(request, list_slug):
    todo_list = get_object_or_404(List, slug=list_slug)

    if todo_list.user != request.user:
        return HttpResponseForbidden("Bu listə icazəniz yoxdur.")

    todos = Todo.objects.filter(
        is_active=True, is_deleted=False, user=request.user, list__slug=list_slug, is_completed=False).order_by("-updated_at")
    favorites = todos.filter(favorites__user=request.user)
    form = TodoForm()

    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            todo = Todo.objects.create(
                title=title, user=request.user, list=todo_list)
            return redirect("todo:todo_view", list_slug=list_slug)

    context = {
        "todo_list": todo_list,
        "todos": todos,
        "favorites": favorites,
        "form": form,
    }
    return render(request, "todo/todo.html", context)


@login_required(login_url="account:login_view")
def todo_favorited_view(request, list_slug):
    todo_list = get_object_or_404(List, slug=list_slug)

    if todo_list.user != request.user:
        return HttpResponseForbidden("Bu listə icazəniz yoxdur.")

    todos = Todo.objects.filter(
        favorites__user=request.user, is_active=True, list__slug=list_slug, is_deleted=False,).order_by("-updated_at")
    favorites = todos.filter(favorites__user=request.user)
    form = TodoForm()

    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            todo = Todo.objects.create(
                title=title, user=request.user, list=todo_list)
            return redirect("todo:todo_view", list_slug=list_slug)

    context = {
        "todo_list": todo_list,
        "todos": todos,
        "favorites": favorites,
        "form": form,
    }
    return render(request, "todo/todo.html", context)


@login_required(login_url="account:login_view")
def add_favorite_view(request, list_slug, todo_slug):
    todo = get_object_or_404(Todo, list__slug=list_slug, slug=todo_slug)

    if todo.is_deleted:
        raise Http404("Bu tapşırıq silinib.")

    if todo.user != request.user:
        return HttpResponseForbidden("Bu tapşırığa icazəniz yoxdur.")

    try:
        favorite = request.user.favorited_by
    except Favorite.DoesNotExist:
        favorite = Favorite.objects.create(user=request.user)

    favorite.add_todo_to_favorites(todo)
    return redirect(request.META.get('HTTP_REFERER', 'todo:todo_view'))


@login_required(login_url="account:login_view")
def remove_favorite_view(request, list_slug, todo_slug):
    todo = get_object_or_404(Todo, list__slug=list_slug, slug=todo_slug)

    if todo.is_deleted:
        raise Http404("Bu tapşırıq silinib.")

    if todo.user != request.user:
        return HttpResponseForbidden("Bu tapşırığa icazəniz yoxdur.")

    request.user.favorited_by.remove_todo_from_favorites(todo)
    return redirect(request.META.get('HTTP_REFERER', 'todo:todo_view'))


@login_required(login_url="account:login_view")
def todo_update_view(request, list_slug, todo_slug):
    todo_list = get_object_or_404(List, slug=list_slug)
    todo = get_object_or_404(Todo, list__slug=list_slug, slug=todo_slug)

    if todo.is_deleted:
        raise Http404("Bu tapşırıq silinib.")

    if todo.user != request.user:
        return HttpResponseForbidden("Bu tapşırığa icazəniz yoxdur.")

    form = TodoDetailForm(instance=todo)

    if request.method == "POST":
        form = TodoDetailForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            messages.success(request, "Məlumatlar uğurla dəyişdirildi.")
            return redirect("todo:todo_view", list_slug=list_slug)

    context = {
        "todo_list": todo_list,
        "todo": todo,
        "form": form,
    }
    return render(request, "todo/update.html", context)


@login_required(login_url="account:login_view")
def todo_detail_view(request, list_slug, todo_slug):
    todo_list = get_object_or_404(List, slug=list_slug)
    todo = get_object_or_404(Todo, list__slug=list_slug, slug=todo_slug)

    if todo.is_deleted:
        raise Http404("Bu tapşırıq silinib.")

    if todo.user != request.user:
        return HttpResponseForbidden("Bu tapşırığa icazəniz yoxdur.")

    is_favorite = Favorite.objects.filter(
        user=request.user, todos__id=todo.id).exists()

    context = {
        "todo_list": todo_list,
        "todo": todo,
        "is_favorite": is_favorite,
    }
    return render(request, "todo/detail.html", context)


@login_required(login_url="account:login_view")
def todo_delete_view(request, list_slug, todo_slug):
    todo = get_object_or_404(Todo, list__slug=list_slug, slug=todo_slug)

    if todo.user != request.user:
        return HttpResponseForbidden("Bu tapşırığa icazəniz yoxdur.")

    todo.is_deleted = True
    todo.save()
    messages.success(
        request, f"Tapşırıq '{todo.title}' zibil qutusuna köçürüldü.")

    return redirect(request.META.get('HTTP_REFERER', 'todo:todo_view'))


@login_required(login_url="account:login_view")
def todo_delete_all_view(request, list_slug):
    todos = Todo.objects.filter(
        is_active=True, user=request.user, list__slug=list_slug)
    todos.update(is_deleted=True)
    messages.success(
        request, "Bütün tapşırıqlar zibil qutusuna köçürüldü.")
    return redirect(request.META.get('HTTP_REFERER', 'todo:todo_view'))

# ========== END Todo ==========


# # =============== Trash ===============

@login_required(login_url="account:login_view")
def trash_view(request):
    deleted_todos = Todo.objects.filter(
        is_active=True, is_deleted=True, user=request.user).order_by("-updated_at")
    context = {
        "deleted_todos": deleted_todos,
    }
    return render(request, 'todo/trash.html', context)

todo/templates/todo/detail.html
{% extends 'base/base.html' %} 


{% block css %}
<style>
  body {
    background-color: lightsalmon;
  }
</style>
{% endblock css %} 

{% block page_title %}
<title>TODO - Təfərrüat</title>
{% endblock page_title %}

{% block content %}
<div class="container">
    <div class="mt-5">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-10 col-md-6">

                <!-- Breadcrumb -->
                <nav class="mt-5" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="/">Əsas Səhifə</a></li>
                      <li class="breadcrumb-item"><a href="{% url 'todo:todo_view' todo_list.slug %}">{{ todo_list.title }}</a></li>
                      <li class="breadcrumb-item active">{{ todo.title }}</li>
                    </ol>
                </nav>
                <!-- END Breadcrumb -->

                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="card-title text-truncate text-wrap">{{ todo.title }}</h5>
                        {% if is_favorite %}
                        <a href="{% url 'todo:remove_favorite_view' todo_list.slug todo.slug %}">
                          <i class="fa-solid fa-star text-warning"></i>
                        </a>
                        {% else %}
                        <a href="{% url 'todo:add_favorite_view' todo_list.slug todo.slug %}">
                          <i class="fa-regular fa-star text-dark"></i>
                        </a>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <p class="card-subtitle mb-2 text-body-secondary">
                            <small class="fst-italic text-muted">Siyahı: </small>
                            <span class="h6">{{ todo.list }}</span>
                        </p>
                        <p class="card-subtitle mb-2 text-body-secondary">
                            <small class="fst-italic text-muted">İstifadəçi: </small>
                            <span class="h6">@{{ todo.user }}</span>
                        </p>
                        <p class="card-text">
                            <small class="fst-italic text-muted"><span>Açıqlama:</span></small>
                            <p>{{ todo.description }}</p>
                        </p>
                        <div>
                            <p class="fst-italic text-muted m-0"><small>Yenilənmə vaxtı: {{ todo.updated_at|date:"d/m/Y H:i" }}</small></p>
                            <p class="fst-italic text-muted"><small>Yaradılma vaxtı: {{ todo.created_at|date:"d/m/Y H:i" }}</small></p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'todo:todo_update_view' todo_list.slug todo.slug %}" class="card-link text-decoration-none">Düzəliş et</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

todo/templates/todo/list.html
{% extends 'base/base.html' %}


{% block css %}
<style>
  body {
    background-color: lightsalmon;
  }
</style>
{% endblock css %} 


{% block page_title %}
<title>TODO - Siyahılar</title>
{% endblock page_title %}


{% block content %}
<div class="container">
  <div class="row mt-5">
    <div class="col">

      <form action="{% url 'todo:list_view' %}" method="POST" class="input-group my-5 w-75">
        {% csrf_token %}
        {{ form.title }}
        <input
          type="submit"
          class="btn btn-primary fw-bold"
          value="Yarat!"
        />
      </form>

      <h3>Siyahılar</h3>
      <hr>

      <!-- Siyahılar -->
      <ul class="list-group mb-5">
        {% for list_item in todo_lists %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <a class="text-decoration-none text-dark" href="{% url 'todo:todo_view' list_item.slug %}">
            {{ list_item.title }}
          </a>
          <div>
            <span class="badge bg-primary rounded-pill">{{ list_item.todos_count }}</span>
            <a href="{% url 'todo:list_delete_view' list_item.slug %}">
              <i class="ms-4 fa-solid fa-trash-can text-danger"></i>
            </a>
          </div>
        </li>
      {% endfor %}
      </ul>
      <!-- END Siyahılar -->

    </div>
  </div>
</div>
{% endblock content %}

todo/templates/todo/todo.html
{% extends 'base/base.html' %} 

{% block css %}
<style>
  body {
    background-color: lightsalmon;
  }
</style>
{% endblock css %} 

{% block page_title %}
<title>TODO - Tapşırıqlar</title>
{% endblock page_title %}

{% block content %}
<div class="container">
  <div class="row mt-5">
    <div class="col">

      <form action="{% url 'todo:todo_view' todo_list.slug %}" method="POST" class="input-group my-5 w-75">
        {% csrf_token %}
        {{ form.title }}
        <input
          type="submit"
          class="btn btn-primary fw-bold"
          value="Əlavə et!"
        />
      </form>

      <h5>
        <span>Siyahı: </span>
        <span class="text-secondary fst-italic">{{ todo_list.title }}</span>
      </h5>
      <h3>Tapşırıqlar</h3>
      <hr>

      <!-- Filter -->
      <div class="btn-group d-flex flex-wrap mb-2">
        <a href="{% url 'todo:todo_view' todo_list.slug %}" class="btn btn-outline-secondary {% if request.resolver_match.view_name == "todo:todo_view" %}active{% endif %}">
          <i class="fas fa-list"></i> Hamısı
        </a>
        <a href="{% url 'todo:todo_completed_view' todo_list.slug %}" class="btn btn-outline-secondary {% if request.resolver_match.view_name == "todo:todo_completed_view" %}active{% endif %}">
          <i class="fas fa-check-circle"></i> Tamamlananlar
        </a>
        <a href="{% url 'todo:todo_uncompleted_view' todo_list.slug %}" class="btn btn-outline-secondary {% if request.resolver_match.view_name == "todo:todo_uncompleted_view" %}active{% endif %}">
          <i class="fas fa-times-circle"></i> Tamamlanmayanlar
        </a>
        <a href="{% url 'todo:todo_favorited_view' todo_list.slug %}" class="btn btn-outline-secondary {% if request.resolver_match.view_name == "todo:todo_favorited_view" %}active{% endif %}">
          <i class="fas fa-star"></i> Favorilər
        </a>
      </div>
      <!-- END Filter -->

      <!-- Result -->
      <div>
        <p class="mb-1 ms-1 fw-italic">{{ todos.count }} nəticə</p>
      </div>
      <!-- END Result -->

      <!-- Table -->
      <div class="table-responsive">
        <table class="table table-sm text-center table-hover">
          <thead class="table-dark">
            <tr>
              <th scope="col" style="width: 40px"></th>
              <th scope="col" >Başlıq</th>
              <th scope="col" style="width: 35px"></th>
              <th scope="col" style="width: 210px">Yenilənmə Vaxtı</th>
              <th scope="col" style="width: 210px">Yaradılma Vaxtı</th>
              <th scope="col" style="width: 35px"></th>
              <th scope="col" style="width: 35px"></th>
              <th scope="col" style="width: 35px"></th>
            </tr>
          </thead>
          <tbody>
            {% for todo in todos %}
            <tr {% if todo.is_completed %}class="table-success"{% endif %}>

              <td>
                <input type="checkbox" {% if todo.is_completed %}checked{% endif %} onclick="toggleCompleted('{{ todo.list.slug }}', '{{ todo.slug }}')" />
              </td>
              <td class="" {% if todo.is_completed %}style="text-decoration: line-through"{% endif %}>{{ todo.title }}</td>
              
              <td>
                {% if todo in favorites %}
                  <a href="{% url 'todo:remove_favorite_view' todo_list.slug todo.slug %}">
                    <i class="fa-solid fa-star text-warning"></i>
                  </a>
                {% else %}
                  <a href="{% url 'todo:add_favorite_view' todo_list.slug todo.slug %}">
                    <i class="fa-regular fa-star text-dark"></i>
                  </a>
                {% endif %}
              </td>
              <td {% if todo.is_completed %}style="text-decoration: line-through"{% endif %}>{{ todo.updated_at|date:"d/m/Y H:i" }}</td>
              <td {% if todo.is_completed %}style="text-decoration: line-through"{% endif %}>{{ todo.created_at|date:"d/m/Y H:i" }}</td>
              <td>
                <a href="{% url 'todo:todo_update_view' todo_list.slug todo.slug %}">
                  <i class="fa-solid fa-pen-to-square"></i>
                </a>
              </td>
              <td>
                <a href="{% url 'todo:todo_delete_view' todo_list.slug todo.slug %}">
                  <i class="fa-solid fa-trash-can text-danger"></i>
                </a>
              </td>
              <td>
                <a href="{% url 'todo:todo_detail_view' todo_list.slug todo.slug %}">
                  <i class="fa-solid fa-eye text-secondary"></i>
                </a>
              </td>
            </tr>
            
            {% empty %}
            <tr>
              <td colspan="8">Hələ ki, heç bir tapşırıq əlavə etməmisiniz.</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- END Table -->

      {% if request.resolver_match.view_name == "todo:todo_view" and todos %}
      <div class="mb-5">
        <a href="{% url 'todo:todo_delete_all_view' todo_list.slug %}" class="btn btn-danger">Hamısını sil</a>
      </div>
      {% endif %}

    </div>
  </div>
</div>
{% endblock content %}

todo/templates/todo/trash.html
{% extends 'base/base.html' %}


{% block css %}
<style>
  body {
    background-color: lightsalmon;
  }
</style>
{% endblock css %}


{% block page_title %}
<title>TODO - Zibil Qutusu</title>
{% endblock page_title %}


{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col">
            <h3>Silinən Tapşırıqlar</h3>
            {% if deleted_todos %}
            <a href="{% url 'todo:empty_trash_view' %}" class="btn btn-danger">Zibil qutusunu boşalt!</a>
            {% endif %}
            <!-- Table -->
            <div class="table-responsive mt-3">
                <table class="table table-sm table-hover">
                    <tbody >
                    {% for todo in deleted_todos %}
                    <tr class="">
                        <td class="text-truncate text-wrap">
                            <span class="ms-1">{{ todo.title }}</span>
                        </td>
                        <td class="text-center" style="width: 45px">
                            <a href="{% url 'todo:restore_todo_view' todo.slug %}">
                                <i class="fa-solid fa-rotate-left text-success"></i>
                            </a>
                        </td>
                        <td class="text-center" style="width: 45px">
                            <a href="{% url 'todo:permanently_delete_todo_view' todo.slug %}">
                                <i class="fa-solid fa-trash text-danger"></i>
                            </a>
                        </td>

                        <td class="text-center" style="width: 130px">
                            (<span class="me-2 text-info">{{ todo.list|truncatechars:10 }}</span>)
                        </td>
                        
                        <td class="text-end" style="width: 150px">
                            <span class="me-2">{{ todo.updated_at|date:"d/m/Y H:i" }}</span>
                        </td>
                    </tr>
                    
                    {% empty %}
                    <tr>
                        <td colspan="8">Zibil qutusu boşdur.</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- END Table -->
        </div>
    </div>
</div>
{% endblock content %}

todo/templates/todo/update.html
{% extends 'base/base.html' %}


{% block css %}
<style>
  body {
    background-color: lightsalmon;
  }
</style>
{% endblock css %}


{% block page_title %}
<title>TODO - Düzəliş</title>
{% endblock page_title %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col col-md-8">

            <!-- Breadcrumb -->
            <nav class="mt-5" aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="/">Əsas Səhifə</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'todo:todo_view' todo_list.slug %}">{{ todo_list.title }}</a></li>
                  <li class="breadcrumb-item active">{{ todo.title }}</li>
                </ol>
            </nav>
            <!-- END Breadcrumb -->

            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="{{ form.title.id_for_label }}" class="form-label fw-bold"
                    >{{ form.title.label }}</label
                  >
                  {{ form.title }}
                </div>
                <div class="mb-3">
                  <label for="{{ form.description.id_for_label }}" class="form-label"
                    >{{ form.description.label }}</label
                  >
                  {{ form.description }}
                </div>
                <button type="submit" class="btn btn-primary">Düzəliş et</button>
              </form>
        </div>
    </div>
</div>
{% endblock content %}