account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path('login/', views.login_view, name="login_view"),
    path('register/', views.register_view, name="register_view"),
    path('logout/', views.logout_view, name="logout_view"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("", include("account.urls", namespace="account")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    # List
    path('', views.list_view, name="list_view"),
    # List Delete
    path('list/<slug:list_slug>/delete',
         views.list_delete_view, name="list_delete_view"),

    # TO-DO Filter
    path('list/<slug:list_slug>/todos/', views.todo_view, name="todo_view"),
    path('list/<slug:list_slug>/todos/completed/',
         views.todo_completed_view, name="todo_completed_view"),
    path('list/<slug:list_slug>/todos/uncompleted/',
         views.todo_uncompleted_view, name="todo_uncompleted_view"),
    path('list/<slug:list_slug>/todos/favorited/',
         views.todo_favorited_view, name="todo_favorited_view"),
    # TO-DO Toggle-Comleted
    path('toggle-completed/<slug:list_slug>/<slug:todo_slug>/',
         views.toggle_completed_view, name='toggle_completed_view'),
    # TO-DO Favorite
    path('list/<slug:list_slug>/todo/<slug:todo_slug>/add-favorite/',
         views.add_favorite_view, name="add_favorite_view"),
    path('list/<slug:list_slug>/todo/<slug:todo_slug>/remove-favorite/',
         views.remove_favorite_view, name="remove_favorite_view"),
    # TO-DO Update
    path('list/<slug:list_slug>/todo/<slug:todo_slug>/update/',
         views.todo_update_view, name="todo_update_view"),
    # TO-DO Delete
    path('list/<slug:list_slug>/todo/<slug:todo_slug>/delete/',
         views.todo_delete_view, name="todo_delete_view"),
    path('list/<slug:list_slug>/todos/delete-all',
         views.todo_delete_all_view, name="todo_delete_all_view"),
    # TO-DO Detail
    path('list/<slug:list_slug>/todo/<slug:todo_slug>/',
         views.todo_detail_view, name="todo_detail_view"),

    # Trash
    path('trash/', views.trash_view, name="trash_view"),
    path('trash/todo/<slug:todo_slug>/restore/',
         views.restore_todo_view, name="restore_todo_view"),
    path('trash/todo/<slug:todo_slug>/permanently-delete/',
         views.permanently_delete_todo_view, name="permanently_delete_todo_view"),
    path('empty-trash/', views.empty_trash_view, name="empty_trash_view"),
]

templates/base/partials/footer.html
<footer class="footer mt-auto p-3 text-center">
  <div class="container">
    <span class="text-muted">— 2023 &copy; Jeyhun Piriyev —</span>
  </div>
</footer>

templates/base/partials/message-alert.html
{% if messages %} {% for message in messages %}
<div
  class="alert alert-{{ message.tags }} alert-dismissible fade show text-center m-0"
  role="alert"
>
  <strong>{{ message }}</strong>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
  {% endfor %}
</div>
{% endif %}

templates/base/partials/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold ms-2" href="/">
      <i class="fa-solid fa-rectangle-list"></i>
      TODO
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto me-5">

        {% if not user.is_authenticated %}
        <li class="nav-item me-3">
          <a
            class="nav-link {% if request.resolver_match.view_name == "account:login_view" %}active{% endif %}"
            href="{% url 'account:login_view' %}"
          >
            <i class="fas fa-sign-in-alt"></i>
            Giriş
          </a>
        </li>
        <li class="nav-item">
          <a 
            class="nav-link {% if request.resolver_match.view_name == "account:register_view" %}active{% endif %}"
            href="{% url 'account:register_view' %}"
          >
            <i class="fa-solid fa-user-plus"></i>
            Qeydiyyat
          </a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="fa-solid fa-user"></i> {{ user.username }}
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.view_name == "todo:trash_view" %}active{% endif %}" href="{% url 'todo:trash_view' %}">
            <i class="fa-solid fa-trash-can"></i> Zibil Qutusu ({{ trash_todo_count_global }})
          </a>
        </li>
        
        <li class="nav-item">
          <a 
            class="nav-link" 
            href="{% url 'account:logout_view' %}"
          >
          Çıxış
          <i class="fa-solid fa-right-from-bracket"></i>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>